/**
 *
 *  InviteTokens.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "InviteTokens.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string InviteTokens::Cols::_id = "id";
const std::string InviteTokens::Cols::_token_hash = "token_hash";
const std::string InviteTokens::Cols::_uses_left = "uses_left";
const std::string InviteTokens::Cols::_created_at = "created_at";
const std::string InviteTokens::Cols::_expires_at = "expires_at";
const std::string InviteTokens::Cols::_enabled = "enabled";
const std::string InviteTokens::primaryKeyName = "id";
const bool InviteTokens::hasPrimaryKey = true;
const std::string InviteTokens::tableName = "invite_tokens";

const std::vector<typename InviteTokens::MetaData> InviteTokens::metaData_={
{"id","int64_t","integer",8,1,1,0},
{"token_hash","std::string","text",0,0,0,1},
{"uses_left","int64_t","integer",8,0,0,1},
{"created_at","int64_t","integer",8,0,0,1},
{"expires_at","int64_t","integer",8,0,0,0},
{"enabled","int64_t","integer",8,0,0,1}
};
const std::string &InviteTokens::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
InviteTokens::InviteTokens(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["token_hash"].isNull())
        {
            tokenHash_=std::make_shared<std::string>(r["token_hash"].as<std::string>());
        }
        if(!r["uses_left"].isNull())
        {
            usesLeft_=std::make_shared<int64_t>(r["uses_left"].as<int64_t>());
        }
        if(!r["created_at"].isNull())
        {
            createdAt_=std::make_shared<int64_t>(r["created_at"].as<int64_t>());
        }
        if(!r["expires_at"].isNull())
        {
            expiresAt_=std::make_shared<int64_t>(r["expires_at"].as<int64_t>());
        }
        if(!r["enabled"].isNull())
        {
            enabled_=std::make_shared<int64_t>(r["enabled"].as<int64_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            tokenHash_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            usesLeft_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            createdAt_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            expiresAt_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            enabled_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
    }

}

InviteTokens::InviteTokens(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            tokenHash_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            usesLeft_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            createdAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            enabled_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
}

InviteTokens::InviteTokens(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("token_hash"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["token_hash"].isNull())
        {
            tokenHash_=std::make_shared<std::string>(pJson["token_hash"].asString());
        }
    }
    if(pJson.isMember("uses_left"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["uses_left"].isNull())
        {
            usesLeft_=std::make_shared<int64_t>((int64_t)pJson["uses_left"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["created_at"].isNull())
        {
            createdAt_=std::make_shared<int64_t>((int64_t)pJson["created_at"].asInt64());
        }
    }
    if(pJson.isMember("expires_at"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["expires_at"].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson["expires_at"].asInt64());
        }
    }
    if(pJson.isMember("enabled"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["enabled"].isNull())
        {
            enabled_=std::make_shared<int64_t>((int64_t)pJson["enabled"].asInt64());
        }
    }
}

void InviteTokens::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            tokenHash_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            usesLeft_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            createdAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            enabled_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
}

void InviteTokens::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("token_hash"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["token_hash"].isNull())
        {
            tokenHash_=std::make_shared<std::string>(pJson["token_hash"].asString());
        }
    }
    if(pJson.isMember("uses_left"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["uses_left"].isNull())
        {
            usesLeft_=std::make_shared<int64_t>((int64_t)pJson["uses_left"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["created_at"].isNull())
        {
            createdAt_=std::make_shared<int64_t>((int64_t)pJson["created_at"].asInt64());
        }
    }
    if(pJson.isMember("expires_at"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["expires_at"].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson["expires_at"].asInt64());
        }
    }
    if(pJson.isMember("enabled"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["enabled"].isNull())
        {
            enabled_=std::make_shared<int64_t>((int64_t)pJson["enabled"].asInt64());
        }
    }
}

const int64_t &InviteTokens::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &InviteTokens::getId() const noexcept
{
    return id_;
}
void InviteTokens::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
void InviteTokens::setIdToNull() noexcept
{
    id_.reset();
    dirtyFlag_[0] = true;
}
const typename InviteTokens::PrimaryKeyType & InviteTokens::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &InviteTokens::getValueOfTokenHash() const noexcept
{
    static const std::string defaultValue = std::string();
    if(tokenHash_)
        return *tokenHash_;
    return defaultValue;
}
const std::shared_ptr<std::string> &InviteTokens::getTokenHash() const noexcept
{
    return tokenHash_;
}
void InviteTokens::setTokenHash(const std::string &pTokenHash) noexcept
{
    tokenHash_ = std::make_shared<std::string>(pTokenHash);
    dirtyFlag_[1] = true;
}
void InviteTokens::setTokenHash(std::string &&pTokenHash) noexcept
{
    tokenHash_ = std::make_shared<std::string>(std::move(pTokenHash));
    dirtyFlag_[1] = true;
}

const int64_t &InviteTokens::getValueOfUsesLeft() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(usesLeft_)
        return *usesLeft_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &InviteTokens::getUsesLeft() const noexcept
{
    return usesLeft_;
}
void InviteTokens::setUsesLeft(const int64_t &pUsesLeft) noexcept
{
    usesLeft_ = std::make_shared<int64_t>(pUsesLeft);
    dirtyFlag_[2] = true;
}

const int64_t &InviteTokens::getValueOfCreatedAt() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &InviteTokens::getCreatedAt() const noexcept
{
    return createdAt_;
}
void InviteTokens::setCreatedAt(const int64_t &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<int64_t>(pCreatedAt);
    dirtyFlag_[3] = true;
}

const int64_t &InviteTokens::getValueOfExpiresAt() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(expiresAt_)
        return *expiresAt_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &InviteTokens::getExpiresAt() const noexcept
{
    return expiresAt_;
}
void InviteTokens::setExpiresAt(const int64_t &pExpiresAt) noexcept
{
    expiresAt_ = std::make_shared<int64_t>(pExpiresAt);
    dirtyFlag_[4] = true;
}
void InviteTokens::setExpiresAtToNull() noexcept
{
    expiresAt_.reset();
    dirtyFlag_[4] = true;
}

const int64_t &InviteTokens::getValueOfEnabled() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(enabled_)
        return *enabled_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &InviteTokens::getEnabled() const noexcept
{
    return enabled_;
}
void InviteTokens::setEnabled(const int64_t &pEnabled) noexcept
{
    enabled_ = std::make_shared<int64_t>(pEnabled);
    dirtyFlag_[5] = true;
}

void InviteTokens::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &InviteTokens::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "token_hash",
        "uses_left",
        "created_at",
        "expires_at",
        "enabled"
    };
    return inCols;
}

void InviteTokens::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTokenHash())
        {
            binder << getValueOfTokenHash();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUsesLeft())
        {
            binder << getValueOfUsesLeft();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getExpiresAt())
        {
            binder << getValueOfExpiresAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEnabled())
        {
            binder << getValueOfEnabled();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> InviteTokens::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void InviteTokens::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTokenHash())
        {
            binder << getValueOfTokenHash();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUsesLeft())
        {
            binder << getValueOfUsesLeft();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getExpiresAt())
        {
            binder << getValueOfExpiresAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEnabled())
        {
            binder << getValueOfEnabled();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value InviteTokens::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTokenHash())
    {
        ret["token_hash"]=getValueOfTokenHash();
    }
    else
    {
        ret["token_hash"]=Json::Value();
    }
    if(getUsesLeft())
    {
        ret["uses_left"]=(Json::Int64)getValueOfUsesLeft();
    }
    else
    {
        ret["uses_left"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=(Json::Int64)getValueOfCreatedAt();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getExpiresAt())
    {
        ret["expires_at"]=(Json::Int64)getValueOfExpiresAt();
    }
    else
    {
        ret["expires_at"]=Json::Value();
    }
    if(getEnabled())
    {
        ret["enabled"]=(Json::Int64)getValueOfEnabled();
    }
    else
    {
        ret["enabled"]=Json::Value();
    }
    return ret;
}

std::string InviteTokens::toString() const
{
    return toJson().toStyledString();
}

Json::Value InviteTokens::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTokenHash())
            {
                ret[pMasqueradingVector[1]]=getValueOfTokenHash();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getUsesLeft())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfUsesLeft();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[3]]=(Json::Int64)getValueOfCreatedAt();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getExpiresAt())
            {
                ret[pMasqueradingVector[4]]=(Json::Int64)getValueOfExpiresAt();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getEnabled())
            {
                ret[pMasqueradingVector[5]]=(Json::Int64)getValueOfEnabled();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTokenHash())
    {
        ret["token_hash"]=getValueOfTokenHash();
    }
    else
    {
        ret["token_hash"]=Json::Value();
    }
    if(getUsesLeft())
    {
        ret["uses_left"]=(Json::Int64)getValueOfUsesLeft();
    }
    else
    {
        ret["uses_left"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=(Json::Int64)getValueOfCreatedAt();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getExpiresAt())
    {
        ret["expires_at"]=(Json::Int64)getValueOfExpiresAt();
    }
    else
    {
        ret["expires_at"]=Json::Value();
    }
    if(getEnabled())
    {
        ret["enabled"]=(Json::Int64)getValueOfEnabled();
    }
    else
    {
        ret["enabled"]=Json::Value();
    }
    return ret;
}

bool InviteTokens::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("token_hash"))
    {
        if(!validJsonOfField(1, "token_hash", pJson["token_hash"], err, true))
            return false;
    }
    else
    {
        err="The token_hash column cannot be null";
        return false;
    }
    if(pJson.isMember("uses_left"))
    {
        if(!validJsonOfField(2, "uses_left", pJson["uses_left"], err, true))
            return false;
    }
    else
    {
        err="The uses_left column cannot be null";
        return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(3, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("expires_at"))
    {
        if(!validJsonOfField(4, "expires_at", pJson["expires_at"], err, true))
            return false;
    }
    if(pJson.isMember("enabled"))
    {
        if(!validJsonOfField(5, "enabled", pJson["enabled"], err, true))
            return false;
    }
    return true;
}
bool InviteTokens::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool InviteTokens::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("token_hash"))
    {
        if(!validJsonOfField(1, "token_hash", pJson["token_hash"], err, false))
            return false;
    }
    if(pJson.isMember("uses_left"))
    {
        if(!validJsonOfField(2, "uses_left", pJson["uses_left"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(3, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("expires_at"))
    {
        if(!validJsonOfField(4, "expires_at", pJson["expires_at"], err, false))
            return false;
    }
    if(pJson.isMember("enabled"))
    {
        if(!validJsonOfField(5, "enabled", pJson["enabled"], err, false))
            return false;
    }
    return true;
}
bool InviteTokens::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool InviteTokens::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
